export enum FILTER {
    FILTER_BY_SPARKLING = 'FILTER_BY_SPARKLING',
    FILTER_BY_NAME = 'FILTER_BY_NAME',
    FILTER_BY_COLOR = 'FILTER_BY_COLOR',
    FILTER_BY_TASTE = 'FILTER_BY_TASTE',
}

export enum CARDS {
    GET_CARDS_BY_FETCH = 'GET_CARDS_BY_FETCH',
    START_FETCH = 'START_FETCH',
    END_FETCH = 'END_FETCH',
}

export enum ERROR {
    FETCH_ERROR = 'FETCH_ERROR',
}
